version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0
jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: '2.4.14'
          with-cache: false
      - ruby/rspec-test
workflows:
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "3.0.3"]
